export default {
  // Logo
  logo: require('../assets/images/logo.png'),

  // Walkthrough images
  welcome: require('../assets/images/welcome.png'),
  delivery: require('../assets/images/delivery.png'),
  connect: require('../assets/images/connect.png'),

  // Tabs icon
  home: require('../assets/icons/home.png'),
  homeFilled: require('../assets/icons/home-filled.png'),
  user: require('../assets/icons/user.png'),
  userFilled: require('../assets/icons/user-filled.png'),
  product: require('../assets/icons/product.png'),
  productFilled: require('../assets/icons/product-filled.png'),
  blog: require('../assets/icons/blog.png'),
  blogFilled: require('../assets/icons/blog-filled.png'),
  cart: require('../assets/icons/cart.png'),
  cartFilled: require('../assets/icons/cart-filled.png'),
  search: require('../assets/icons/search.png'),
  filter: require('../assets/icons/filter.png'),
  back: require('../assets/icons/back.png'),
  moreLight: require('../assets/icons/more_white.png'),

  // Anything
  name: require('../assets/icons/name.png'),
  phone: require('../assets/icons/phone.png'),
  email: require('../assets/icons/email.png'),
  password: require('../assets/icons/password.png'),
  calendar: require('../assets/icons/calendar.png'),
  gender: require('../assets/icons/gender.png'),
  star: require('../assets/icons/star.png'),
  plus: require('../assets/icons/plus.png'),
  subtract: require('../assets/icons/subtract.png'),
  delete: require('../assets/icons/delete.png'),
  information: require('../assets/icons/information.png'),
  address: require('../assets/icons/address.png'),
  order: require('../assets/icons/order.png'),
  confirming_status: require('../assets/icons/confirming_status.png'),
  done_status: require('../assets/icons/done_status.png'),
  delivering_status: require('../assets/icons/delivering_status.png'),
  error_status: require('../assets/icons/error_status.png'),
  transaction: require('../assets/icons/transaction.png'),
  logout: require('../assets/icons/logout.png'),
  edit: require('../assets/icons/edit.png'),
  street: require('../assets/icons/street.png'),
  district: require('../assets/icons/district.png'),
  city: require('../assets/icons/city.png'),
  country: require('../assets/icons/country.png'),
  camera_light: require('../assets/icons/camera_light.png'),
  eye: require('../assets/icons/eye.png'),
  blind: require('../assets/icons/blind.png'),
};
